


           
<!--
                    <form name ="xx" class="form-horizontal" method="post">
                        <fieldset>
                            <legend>Feedback Form</legend>
                            <div class="error-msg"><?php echo $this->errorMessage ?></b></div>
                           <?php echo $this->form; ?>

    <div class="form-actions">

        <input type="submit" name="submit" value="submit" style="background-color: #0088CC;
width: 100px;
color: white;">
    </div>
                        </fieldset>
                        
                    </form> -->

                    <hr>
                  
               
            <!-- Le javascript
            ================================================== -->
            <!-- Placed at the end of the document so the pages load faster -->
            <script src="../assets/js/jquery.js"></script>
            <script src="../assets/js/bootstrap-transition.js"></script>
            <script src="../assets/js/bootstrap-alert.js"></script>
            <script src="../assets/js/bootstrap-modal.js"></script>
            <script src="../assets/js/bootstrap-dropdown.js"></script>
            <script src="../assets/js/bootstrap-scrollspy.js"></script>
            <script src="../assets/js/bootstrap-tab.js"></script>
            <script src="../assets/js/bootstrap-tooltip.js"></script>
            <script src="../assets/js/bootstrap-popover.js"></script>
            <script src="../assets/js/bootstrap-button.js"></script>
            <script src="../assets/js/bootstrap-collapse.js"></script>
            <script src="../assets/js/bootstrap-carousel.js"></script>
            <script src="../assets/js/bootstrap-typeahead.js"></script>