<?php $locale = Zend_Registry::get('Zend_Locale');


?>
<html>
<head>
    <meta charset="utf-8">
    <title>AIMS Ghana</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href=<?php APPLICATION_PATH ?>"/assets/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href=<?php APPLICATION_PATH ?>"/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
</head>
<body>
    
    
<div class="navbar navbar-fixed-top">
     
    <div class="navbar-inner" style="color: white;
font-size: 28px;
padding-top: 8px;">
        AIMS Ghana
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <?php  $auth = Zend_Auth::getInstance();

        if ($auth->hasIdentity()) {
            $this->user = $auth->getIdentity();?>
             <a class="brand" href="/user/logout" style="float:right">Logout</a>
        <?php }else{?>
            <a class="brand" href="/user/login" style="float:right">Login</a>
            <?php } ?>
            <div class="nav-collapse">
                <!--<ul class="nav">
                  <li class="active"><a href="#">Home</a></li>
                  <li><a href="#about">About</a></li>
                  <li><a href="#contact">Contact</a></li>
                </ul>-->
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>
    
    <div class="container">
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span3">
                <div class="well sidebar-nav">
                    <img src="/img/sideBanner1.jpg" alt="AIMS Ghana" />
                   <!-- <ul class="nav nav-list">
                        <li class="nav-header">####</li>
                        <li class="active"><a href="#">MTA International</a></li>
                        <li><a href="#">###</a></li>
                        <li><a href="#">####</a></li>
                        <li><a href="#">#######</a></li>
                        <li><a href="#">T###</a></li>
                        <li><a href="#">#########</a></li>
                        <li class="nav-header">Conference</li>
                        <li><a href="#">###</a></li>
                        <li><a href="#">S##L</a></li>
                        <li><a href="#">####</a></li>
                        <li><a href="#">#####</a></li>
                        <li><a href="#">###</a></li>
                    </ul>-->
                </div><!--/.well -->
            </div><!--/span-->
     <div class="span9">
                <div class="leaderboard">
    <?php echo $this->layout()->content ?>
                    
                    
                     </div><!--/.fluid-container-->

            </div> <!-- /container -->
            
                    
            
        </div>
         
    </div>
        <footer style="float: right">
                        <p>&copy; AIMS Ghana</p>
                    </footer>
    </div>
    
</body>
</html>


