<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
<script> 
    $(function () {
    	
        // Radialize the colors
        Highcharts.getOptions().colors = Highcharts.map(Highcharts.getOptions().colors, function(color) {
            return {
                radialGradient: { cx: 0.5, cy: 0.3, r: 0.7 },
                stops: [
                    [0, color],
                    [1, Highcharts.Color(color).brighten(-0.3).get('rgb')] // darken
                ]
            };
        });
</script>

<div class="span9">
    <div class="leaderboard">

        <?php
        $another = $this->data;
        $i = 0;
        foreach ($another as $key) {
            foreach ($key as $key1 => $value) {
                $questionId = $value['questionId'];
            }

            $questionName = new Application_Model_Users();
            $result = $questionName->getQuestion($questionId);
            ?>

            <script> 
                    $(function () {
        	
        	
    		
                        // Build the chart
                        $('#container<?php echo $i ?>').highcharts({
                            chart: {
                                plotBackgroundColor: null,
                                plotBorderWidth: null,
                                plotShadow: false
                            },
                          exporting: { enabled: false },
                            credits : {
                                enabled : false
                            },
                            title: {
                                text: '<?php echo $result; ?>'
                            },
                            tooltip: {
                                pointFormat: '{series.name}: <b>{point.percentage}%</b>',
                                percentageDecimals: 1
                            },
                            plotOptions: {
                                pie: {
                                    allowPointSelect: true,
                                    cursor: 'pointer',
                                    dataLabels: {
                                        enabled: true,
                                        color: '#000000',
                                        connectorColor: '#000000',
                                        formatter: function() {
                                            return '<b>'+ this.point.name +'</b>: '+ this.percentage.toFixed(2) + ' %';
                                        }
                                    }
                                }
                            },
                            series: [{
                                    type: 'pie',
                                    name: '',
                                    data: [
    <?php foreach ($key as $key1 => $value) { ?>
                                                        ['<?php echo $value['answer']; ?>',   <?php echo $value['total_answer']; ?>],
                      
    <?php } ?>
                        
                        
                                       ]
                                   }]
                           });
                       });
        
            </script>
            <div id="container<?php echo $i; ?>" style="min-width: 400px; height: 400px; margin: 0 auto"></div>
            <?php
            $i++;
        }
        ?>
    </div>
</div>