
<div class="span9">
    <div class="leaderboard">
        <br/>
        <div>
            <?php if ($this->messages) {
                foreach ($this->messages as $message) {
                    ?>
                    <p class="text-error"><?php echo $message; ?></p>
            <?php }} ?>

        </div>
        <div>
            <form action="" method="post">
                <fieldset><legend>Choose Year</legend>

<?php echo $this->form; ?>
                    <input type="submit" value="Go" name="submit" class="btn btn-primary">

                </fieldset>
            </form>
        </div>
        <div>
<?php if ($this->data) { ?>

                <table class="table table-bordered table-striped">
                    <caption style="font-weight: bold">yearly report for financial year <?php echo $this->current_year; ?></caption>
                    <thead>
                        <tr>
                            <?php foreach ($this->data as $key => $value) { ?>
                                <th style="font-size: 11px"><?php echo $key ?></th>
    <?php } ?>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <?php foreach ($this->data as $value) { ?>
                                <td>$<?php echo $value ?></td>
    <?php } ?>
                        </tr>
                    </tbody>
                </table>
                <div>
                    <a class ="btn btn-large btn-primary" href="/user/dashboard">Go to Dashboard</a>
                </div>
<?php } ?>
        </div>

    </div><!--/.fluid-container-->

</div> <!-- /container -->
