<div class="span9">
    <div class="leaderboard">


        <fieldset>
            <legend>Chanda Receipt</legend>
            <div class="errors"><?php echo $this->errorMessage ?></b></div>

            <div>
                <span> <b>Name: </b> <?php
echo $this->user['first_name'];
echo ' ' . $this->user['last_name'];
?></span>
                <span><b>Tajneed: </b><?php echo $this->user['tajneed']; ?></span>
            </div>
            <br/>
            <div>
                <span><b>Age: </b><?php echo $this->user['age']; ?></span>
                <span><b>Jamaat: </b><?php echo $this->jamaat; ?></span>
            </div>



        </fieldset>

        <fieldset>
           

            <table class="table table-striped">
                <caption>Receipt No: </b><?php echo $this->receiptno; ?></caption>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Cateogry</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->data as $data) { ?>
                    <tr>
                        <td>#</td>
                        <td><?php echo $data['receipt_type'] ?></td>
                        <td><?php echo $data['value'] ?></td>
                    </tr>
                    <?php } ?>
                    <tr>
                        <td></td>
                        <td>Total</td>
                        <td><?php echo $this->total; ?></td>
                    </tr>
                </tbody>
            </table>
       
        </fieldset>

       

    </div><!--/.fluid-container-->
    <div>
        <p><a class="btn btn-large btn-primary " href="/receipt/form/user_id/<?php echo $this->user['ID'];?>">Add Receipt for same member</a>
        <a class="btn btn-large btn-primary " href="/receipt/index">Add Receipt for new member</a>
        <a class="btn btn-large btn-primary " href="/user/dashboard">Go to Dashboard</a>
        </p>
    </div>

</div> <!-- /container -->

